<a href="https://colab.research.google.com/github/mabrarbel-eng/DSC110/blob/main/Description__week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

#DataFrame in Python is the equivalent of table in SQL
df = pd.read_csv("https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv") #reading csv raw link from GitHub

In [6]:
df.head ()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [7]:
df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [8]:
df.head(20)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
5,130383.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
6,130384.0,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN
7,130385.0,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN
8,130386.0,1.0,34.0,1.0,4.0,30.2,173.3,110.0,2.0,5.1,100.0
9,130387.0,2.0,68.0,3.0,5.0,42.6,155.9,143.0,2.0,5.9,NaN
10,130388.0,2.0,27.0,4.0,4.0,43.7,168.2,130.0,2.0,4.9,NaN
11,130389.0,1.0,59.0,3.0,5.0,28.0,168.9,145.0,2.0,5.5,NaN
12,130390.0,2.0,31.0,3.0,3.0,46.0,163.3,113.0,2.0,5.9,NaN
13,130391.0,2.0,33.0,3.0,3.0,38.9,172.8,105.0,2.0,5.4,NaN
14,130392.0,2.0,74.0,3.0,5.0,43.0,151.5,154.0,2.0,5.6,NaN
15,130393.0,1.0,39.0,3.0,5.0,46.1,175.6,139.0,2.0,5.3,NaN
16,130394.0,1.0,51.0,3.0,5.0,24.4,177.3,99.0,2.0,4.8,88.0
17,130395.0,2.0,33.0,7.0,3.0,54.6,159.2,112.0,2.0,5.0,100.0
18,130396.0,2.0,56.0,3.0,4.0,27.3,154.9,122.0,2.0,5.0,104.0
19,130397.0,2.0,67.0,3.0,3.0,49.7,161.8,157.0,2.0,6.2,138.0

In [10]:
df.tail(10)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11923,142301.0,2.0,80.0,3.0,5.0,30.5,164.3,NaN,2.0,5.6,110.0
11924,142302.0,1.0,70.0,3.0,4.0,21.4,161.5,126.0,2.0,5.2,NaN
11925,142303.0,2.0,69.0,7.0,3.0,27.9,159.2,129.0,1.0,8.1,160.0
11926,142304.0,1.0,14.0,2.0,NaN,18.5,162.4,116.0,2.0,NaN,NaN
11927,142305.0,2.0,76.0,1.0,1.0,26.4,151.4,139.0,3.0,6.0,132.0
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [11]:
df.shape
(11933,11)

(11933, 11)

In [12]:
df.shape

(11933, 11)

In [13]:
df.shape[0]
11933

11933

In [14]:
df.shape[1]
11

11

In [15]:
n_rows = df.shape[0]

In [18]:
n_rows = df.shape[0]
n_cols = df.shape[1]
print(f"My dataset contains {n_rows} rows and {n_cols} columns")

My dataset contains 11933 rows and 11 columns

In [ ]:
Boolean

In [21]:
1 + 1 == 3

False

In [22]:
1 + 1 == 2

True

In [23]:
True + True

2

In [24]:
True + False

1

In [ ]:
Data Cleaning

In [26]:
#Missing values
#How big of a problem?
df ['bmi'].head()

0    27.0
1    33.5
2    29.7
3    23.8
4     NaN
Name: bmi, dtype: float64

In [28]:
#isna
#This function checks whether each row is na or not
df['bmi'].isna().head()

0    False
1    False
2    False
3    False
4     True
Name: bmi, dtype: bool

In [29]:
df['bmi'].isna().sum()

np.int64(3462)

In [ ]:
We'll create a new dataset for people over 18 year only and see how many BMI values are missing.

In [30]:
df_adults = df[df['age']> 18 ]

In [31]:
df_adults['age'].min()

19.0

In [ ]:
df_adults['bmi'].isna().sum()

In [ ]:
Now it's your turn to do the same for education and have the output in f string

In [33]:
missing_ed_adults = df_adults['education'].isna().sum()

In [34]:
#Getting missingness as percentage
df.isna

In [36]:
round(df.isna().mean()*100,1)

id                  0.0
gender              0.0
age                 0.0
race_ethnicity      0.0
education          34.7
bmi                29.0
height_cm          28.8
systolic_bp        37.0
has_diabetes        1.6
hba1c              43.7
fasting_glucose    69.2
dtype: float64

In [ ]:
#drop all rows that have any missing value
#df_complete = df.dropna()